// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1450.FRCSteamworks;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import java.io.DataInputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;

import org.usfirst.frc1450.FRCSteamworks.commands.*;
import org.usfirst.frc1450.FRCSteamworks.commands.driveCommands.AutonomousArcadeDrive;
import org.usfirst.frc1450.FRCSteamworks.commands.driveCommands.CameraBasedTurn;
import org.usfirst.frc1450.FRCSteamworks.commands.driveCommands.MiddleLiftCommandGroup;
import org.usfirst.frc1450.FRCSteamworks.commands.gearShiftCommands.HomeGearShift;
import org.usfirst.frc1450.FRCSteamworks.subsystems.*;


/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot{

    Command autonomousCommand;
    Command teleopDriveCommand;

    public static OI oi;
    public static Drives drives;
    public static GearShift gearShift;
    public static Climber climber;
    public static GearRelease gearRelease;
    
    // Server variables
    private ServerSocket server = null; //server
	private Socket client = null; //client 
	public String data = ""; //client message held here for usage <Distance, Direction>
	private DataInputStream input; //temporary placeholder for client input
	private PrintStream output; //message to send to client (Start or Stop flags)
    private static final int port = 5800; //server socket port
    public double secondsPerLoop = 0.02;
    
    public boolean startAuto = false; //flag to start the autonomous round
    
    SendableChooser<Command> chooser;

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
	public void robotInit() {
		RobotMap.init();
        drives = new Drives();
        gearShift = new GearShift();
        climber = new Climber();
        gearRelease = new GearRelease();

        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // instantiate the command used for the autonomous period
        chooser = new SendableChooser<Command>();
        chooser.addDefault("Middle Lift", new AutonomousArcadeDrive(Robot.drives.encodersPerInch*77.5, 10.0));	//114.3" - 36" = 78" 
        chooser.addObject("Left Lift", new leftHookAutonomousCommandGroup());
        chooser.addObject("Right Lift", new rightHookAutonomousCommandGroup());
        //chooser.addObject("Home Gear Shift", new HomeGearShift(15.0));
        chooser.addObject("Do Nothing", new AutonomousCommand());
        //chooser.addObject("CameraTurn", new CameraBasedTurn(30.0));
        //chooser.addObject("MidLiftCmdGroup", new MiddleLiftCommandGroup());
        SmartDashboard.putData("Autonomous Mode Chooser", chooser);
        autonomousCommand = new AutonomousArcadeDrive(Robot.drives.encodersPerInch*77.5, 10.0);
        SmartDashboard.putNumber("climbVolts", 12.0);
        SmartDashboard.putNumber("maxSpeed", 100.0);
        //SmartDashboard.putNumber("PropGain", 0.15);		//0.22 velocity control
        //SmartDashboard.putNumber("IntGain", 0.0015);	//0.0022 velocity control
        //SmartDashboard.putNumber("DerGain", 0.0);
        //SmartDashboard.putNumber("FGain", 0.0);
        SmartDashboard.putNumber("BriansNotSoBright", 30);
        SmartDashboard.putNumber("TurnPercent", 50);
        SmartDashboard.putNumber("SlowSpeed", 0.2);
        //SmartDashboard.putString("AutoState", "Off");
        //SmartDashboard.putNumber("CamOffsetAngle", 3.0);
        
        Robot.drives.initCamera();
        Robot.drives.VoltageControl();
        Robot.gearShift.initGearShift();
		
        // Attempt to create the server and connect a client
		serverThread.start(); //thread started for server-client communication

    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){
    	if (server != null)
    	{
	    	try {
				server.close();							//try to close server. maybe we should send shutdown command to R.Pi
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    	SmartDashboard.putString("AutoState", "Off");
    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
    	Robot.drives.EnableBraking();							//enable braking so we get better position control
    	Robot.drives.ClearGyroAngle();							//clear gyro angle so we start at angle reference 0
        startAuto = true;										//signal server thread that auto has started
        autonomousCommand = (Command) chooser.getSelected();	//grab user selected autonomous routine
        if (autonomousCommand != null)							//if everything is fine then run selected auto routine
        {
        	autonomousCommand.start();
        }
        else													//if something went wrong then run routine for middle lift
        {
        	autonomousCommand = new AutonomousArcadeDrive(Robot.drives.encodersPerInch*77.5, 10.0);
        	autonomousCommand.start();
        }
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
    	if (server != null)
    	{
	    	try {
				server.close();							//try to close server. maybe we should send shutdown command to R.Pi
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
        if (autonomousCommand != null) autonomousCommand.cancel();
        Robot.drives.DisableBraking();				//disable braking as it is stressful to motors/controllers
        Robot.drives.StopVelocityControl();			//make sure robot isn't trying to go anywhere
    	Robot.drives.VoltageControl();				//switch back to voltage control for teleop joystick operation
    	try {
			server.close();							//try to close server. maybe we should send shutdown command to R.Pi
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
    }

    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
    }
    
    /*
     * (non-Javadoc)
     * @see java.lang.Runnable#run()
     */
    @SuppressWarnings("deprecation")
	Thread serverThread = new Thread(() -> {
		while (true){
	    	try {
				server = new ServerSocket(port); //create server
				SmartDashboard.putString("Note1","Server has been made");
				client = server.accept(); //blocking call to connect to client
				input = new DataInputStream(client.getInputStream());
				output = new PrintStream(client.getOutputStream());
				
				int debugLoop = 0;
	    		
				while(true){
					SmartDashboard.putString("Note2","Client connected. Waiting for message");
					
					while(startAuto == false)
					{
						debugLoop++;
						SmartDashboard.putNumber("debugCount", debugLoop);
					}

					output.println("<Start>"); //START AUTONOMOUS MODE 
					
					data = input.readLine(); //blocking call
					
					if(data == null){
						server.close();
						break;
					}
					
					SmartDashboard.putString("Data", data);
				}
	    	}
			catch (IOException e) {
				e.printStackTrace();
				SmartDashboard.putString("Test", "Something happened");
			}
			
		}
	});
}
